### PR TITLE
Add GitHub Extended

### PR DESCRIPTION
**Pull request by onmyway133**
Hi, some people just have more than 5 cool repositories to show, so I make this https://github.com/onmyway133/github-extended

### CODE REVIEW

**Comment by xhacker** [comment]
Awesome, thank you! Can you update the json instead of md? [Instruction here](https://github.com/xhacker/awesome-github-extensions/blob/master/CONTRIBUTING.md).

**Comment by onmyway133** [comment]
@xhacker Hi, what is the json used for?

**Comment by xhacker** [comment]
It's used for generating the md file so that you don't need to care about all the icons etc.

**Comment by onmyway133** [comment]
@xhacker I don't think it is worth the effort. Normally people use GitHub on web to create pull requests to README, quick and simple. And that Python script just generate too little stuff. Just my opinion

**Comment by xhacker** [comment]
Hi @onmyway133: I’ve added your extension in 7ec3156964298e3b191ed994edf0018be57b4711. Thanks!

**Comment by onmyway133** [comment]
@xhacker many thanks 👍

**Pull request closed without merging**
